language: ruby
script: bundle exec rake test
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.0
  - jruby-19mode
before_install:
  - gem install bundler
matrix:
  fast_finish: true
